# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(max_length=16)),
                ('mobile', models.CharField(max_length=13, verbose_name=b'Mobile')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('accessToken', models.CharField(max_length=16)),
            ],
        ),
    ]
