# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('DeviceId', models.CharField(max_length=16)),
                ('Mobile', models.CharField(max_length=13, verbose_name=b'Mobile')),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('AccessToken', models.CharField(max_length=16)),
                ('Name', models.CharField(max_length=100)),
                ('EmailId', models.EmailField(max_length=254)),
                ('FbId', models.CharField(max_length=25)),
                ('GoogleId', models.CharField(max_length=25)),
            ],
        ),
    ]
