# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plan', '0001_initial'),
        ('signup', '0002_auto_20160119_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('ItineraryId', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('ItineraryName', models.CharField(max_length=20)),
                ('StartTime', models.TimeField(default='09:00:00')),
                ('EndTime', models.TimeField(default='17:00:00')),
                ('StartLatitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('StartLongitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('EndLatitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('EndLongitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.User')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.PositiveIntegerField(default=0)),
                ('StartTime', models.TimeField(default='09:00:00')),
                ('TimeToReach', models.DurationField(default='00:30:00')),
                ('Duration', models.DurationField(default='00:30:00')),
                ('ItineraryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerary.Itinerary')),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan.MumbaiLocation')),
            ],
        ),
    ]
