# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0002_route'),
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.TimeField(default='09:00:00')),
                ('Duration', models.DurationField(default='00:30:00')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.TimeField(default='09:00:00')),
                ('Duration', models.DurationField(default='00:30:00')),
            ],
        ),
        migrations.RenameModel(
            old_name='Itinerary',
            new_name='ItineraryInput',
        ),
        migrations.RemoveField(
            model_name='itineraryinfo',
            name='ItineraryId',
        ),
        migrations.RemoveField(
            model_name='itineraryinfo',
            name='LocationId',
        ),
        migrations.DeleteModel(
            name='ItineraryInfo',
        ),
        migrations.AddField(
            model_name='itineraryroute',
            name='ItineraryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerary.ItineraryInput'),
        ),
        migrations.AddField(
            model_name='itineraryroute',
            name='RouteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan.MumbaiLocation'),
        ),
        migrations.AddField(
            model_name='itinerarydestination',
            name='ItineraryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerary.ItineraryInput'),
        ),
        migrations.AddField(
            model_name='itinerarydestination',
            name='LocationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan.MumbaiLocation'),
        ),
    ]
