# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MumbaiLocation',
            fields=[
                ('LocationId', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('Longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('OpenTime', models.TimeField(default=b'09:00:00')),
                ('DueTime', models.TimeField(default=b'17:00:00')),
                ('ServiceTime', models.DurationField(default=b'01:00:00')),
                ('GeneralInfo', models.FilePathField(default=b'./')),
                ('Cost', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
