# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MumbaiLocation',
            fields=[
                ('LocationId', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('Longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('OpenTime1', models.TimeField(default=b'09:00:00')),
                ('DurationOpen1', models.DurationField(default=b'03:00:00')),
                ('OpenTime2', models.TimeField(default=b'09:00:00')),
                ('DurationOpen2', models.DurationField(default=b'03:00:00')),
                ('ServiceTime', models.DurationField(default=b'01:00:00')),
                ('GeneralInfo', models.FilePathField(path=b'./')),
                ('Cost', models.PositiveIntegerField(default=0)),
                ('MondayOpen', models.BooleanField(default=True)),
                ('TuesdayOpen', models.BooleanField(default=True)),
                ('WednesdayOpen', models.BooleanField(default=True)),
                ('ThursdayOpen', models.BooleanField(default=True)),
                ('FridayOpen', models.BooleanField(default=True)),
                ('SaturdayOpen', models.BooleanField(default=False)),
                ('SundayOpen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MumbaiTagLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weightage', models.PositiveSmallIntegerField(default=1)),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan.MumbaiLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('RouteId', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('Slot11', models.DurationField(default=b'00:30:00')),
                ('Slot21', models.DurationField(default=b'00:30:00')),
                ('Slot31', models.DurationField(default=b'00:30:00')),
                ('Slot41', models.DurationField(default=b'00:30:00')),
                ('Slot51', models.DurationField(default=b'00:30:00')),
                ('Slot12', models.DurationField(default=b'00:30:00')),
                ('Slot22', models.DurationField(default=b'00:30:00')),
                ('Slot32', models.DurationField(default=b'00:30:00')),
                ('Slot42', models.DurationField(default=b'00:30:00')),
                ('Slot52', models.DurationField(default=b'00:30:00')),
                ('Destination1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destination1', to='Plan.MumbaiLocation')),
                ('Destination2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destination2', to='Plan.MumbaiLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('TagId', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('TagName', models.CharField(max_length=50)),
                ('TagInfo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mumbaitaglocation',
            name='TagId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan.Tag'),
        ),
    ]
