# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mumbailocation',
            name='GeneralInfo',
            field=models.FilePathField(path=b'./'),
        ),
    ]
