# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0002_auto_20160117_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='MumbaiTagLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weightage', models.PositiveSmallIntegerField(default=1)),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan.MumbaiLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('TagId', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('TagName', models.CharField(max_length=50)),
                ('TagInfo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mumbaitaglocation',
            name='TagId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plan.Tag'),
        ),
    ]
